version: "3.3"
services:
  db:
    image: postgres:13.1
    volumes:
      - ./poster_commenter_db:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=poster_commenter
      - POSTGRES_USER=tdeveloper
      - POSTGRES_PASSWORD=tdeveloper
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend:
    depends_on:
      - db
    build:
      context: ./project
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./project:/app
    command: python3 manage.py runserver 0.0.0.0:8000
