# Generated by Django 3.1.6 on 2021-03-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
    ]
